language: python
python:
  - "2.7"
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install coverage
  - pip install pytest
  - pip install mock
# command to run tests
script:
  - coverage run --source=Tea -m pytest tests/
  - wget --no-check-certificate https://codecov.io/bash -O codecov.sh
  - bash codecov.sh -cF "python"