language: python
python:
  - "2.7"
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
# command to install dependencies
install:
  - pip install coverage pytest mock
# command to run tests
script:
  - coverage run --source=Tea -m pytest tests/
  - wget --no-check-certificate https://codecov.io/bash -O codecov.sh
  - bash codecov.sh -cF "python"